name: nightly-e2e-tests

on:
  schedule:
    - cron:  '* 23 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory
        id: yarn-cache
        if: runner.os == 'Linux'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Save/restore yarn cache
        uses: actions/cache@v1
        if: runner.os == 'Linux'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn build
      - run: yarn run test:e2e
        env:
          CI: true
